{'disciplinas': [{'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 1,
                                   'slice_i': 0},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 3,
                                   'slice_i': 1},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 5,
                                   'slice_i': 3}],
                  'grade': 'p7',
                  'horas': [2, 2],
                  'nome': 'Instrumentação Eletrônica',
                  'num_alunos': 10,
                  'professores': [{'afinidade': 2, 'nome': 'Cícero'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 6,
                                   'slice_i': 5},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 8,
                                   'slice_i': 6},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 10,
                                   'slice_i': 8}],
                  'grade': 'p7',
                  'horas': [2, 3],
                  'nome': 'Máquinas Elétricas',
                  'num_alunos': 20,
                  'professores': [{'afinidade': 1, 'nome': 'Fabiano'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 11,
                                   'slice_i': 10},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 13,
                                   'slice_i': 11},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 15,
                                   'slice_i': 13}],
                  'grade': 'p7',
                  'horas': [2, 3],
                  'nome': 'Controle I',
                  'num_alunos': 15,
                  'professores': [{'afinidade': 2, 'nome': 'Alexsandro'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 16,
                                   'slice_i': 15},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 18,
                                   'slice_i': 16},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 20,
                                   'slice_i': 18}],
                  'grade': 'p7',
                  'horas': [2, 3],
                  'nome': 'Princípios de Comunicações',
                  'num_alunos': 12,
                  'professores': [{'afinidade': 2, 'nome': 'Fabrício'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 21,
                                   'slice_i': 20},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 23,
                                   'slice_i': 21},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 25,
                                   'slice_i': 23}],
                  'grade': 'p7',
                  'horas': [2, 3],
                  'nome': 'Sistemas Elétricos',
                  'num_alunos': 20,
                  'professores': [{'afinidade': 2, 'nome': 'Clivaldo'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 26,
                                   'slice_i': 25},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 28,
                                   'slice_i': 26},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 30,
                                   'slice_i': 28}],
                  'grade': 'p7',
                  'horas': [2, 3],
                  'nome': 'Eletrônica de Potência',
                  'num_alunos': 25,
                  'professores': [{'afinidade': 2, 'nome': 'Romero'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 31,
                                   'slice_i': 30},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 33,
                                   'slice_i': 31},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 35,
                                   'slice_i': 33}],
                  'grade': 'p8',
                  'horas': [2, 2],
                  'nome': 'Técnicas de Medição',
                  'num_alunos': 22,
                  'professores': [{'afinidade': 2, 'nome': 'Yuri'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 36,
                                   'slice_i': 35},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 38,
                                   'slice_i': 36},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 40,
                                   'slice_i': 38}],
                  'grade': 'p8',
                  'horas': [2, 2],
                  'nome': 'Análise de Sistemas Elétricos',
                  'num_alunos': 15,
                  'professores': [{'afinidade': 2, 'nome': 'Helon'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 41,
                                   'slice_i': 40},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 43,
                                   'slice_i': 41},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 45,
                                   'slice_i': 43}],
                  'grade': 'p8',
                  'horas': [2, 2],
                  'nome': 'Filtros',
                  'num_alunos': 15,
                  'professores': [{'afinidade': 2, 'nome': 'Euler'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 46,
                                   'slice_i': 45},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 48,
                                   'slice_i': 46},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 50,
                                   'slice_i': 48}],
                  'grade': 'p8',
                  'horas': [2, 2],
                  'nome': 'Instrumentação Industrial',
                  'num_alunos': 15,
                  'professores': [{'afinidade': 2, 'nome': 'Carlos'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 51,
                                   'slice_i': 50},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 53,
                                   'slice_i': 51},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 55,
                                   'slice_i': 53}],
                  'grade': 'p8',
                  'horas': [2, 2],
                  'nome': 'Acionamentos e Circuitos Elétricos',
                  'num_alunos': 15,
                  'professores': [{'afinidade': 2, 'nome': 'Isaac'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]},
                 {'cromossomos': [{'limite_inferior': 0,
                                   'limite_superior': 1,
                                   'numero_genes': 1,
                                   'slice_f': 56,
                                   'slice_i': 55},
                                  {'limite_inferior': 0,
                                   'limite_superior': 4,
                                   'numero_genes': 2,
                                   'slice_f': 58,
                                   'slice_i': 56},
                                  {'limite_inferior': 0,
                                   'limite_superior': 60,
                                   'numero_genes': 2,
                                   'slice_f': 60,
                                   'slice_i': 58}],
                  'grade': 'p8',
                  'horas': [2, 2],
                  'nome': 'Microc e Microp',
                  'num_alunos': 15,
                  'professores': [{'afinidade': 2, 'nome': 'Protásio'}],
                  'salas': [{'capacidade': 30, 'nome': 'CTM1'},
                            {'capacidade': 30, 'nome': 'CTM2'},
                            {'capacidade': 30, 'nome': 'CTM3'},
                            {'capacidade': 30, 'nome': 'CTM4'}]}],
 'grades': ['p7', 'p8'],
 'horarios': ['2M1',
              '2M2',
              '2M3',
              '2M4',
              '2M5',
              '2T1',
              '2T2',
              '2T3',
              '2T4',
              '2T5',
              '3M1',
              '3M2',
              '3M3',
              '3M4',
              '3M5',
              '3T1',
              '3T2',
              '3T3',
              '3T4',
              '3T5',
              '4M1',
              '4M2',
              '4M3',
              '4M4',
              '4M5',
              '4T1',
              '4T2',
              '4T3',
              '4T4',
              '4T5',
              '5M1',
              '5M2',
              '5M3',
              '5M4',
              '5M5',
              '5T1',
              '5T2',
              '5T3',
              '5T4',
              '5T5',
              '6M1',
              '6M2',
              '6M3',
              '6M4',
              '6M5',
              '6T1',
              '6T2',
              '6T3',
              '6T4',
              '6T5',
              '7M1',
              '7M2',
              '7M3',
              '7M4',
              '7M5',
              '7T1',
              '7T2',
              '7T3',
              '7T4',
              '7T5'],
 'professores': [{'disciplinas': {'Instrumentação Eletrônica': 2},
                  'hrs_max': 12,
                  'hrs_min': 8,
                  'nome': 'Cícero'},
                 {'disciplinas': {'Máquinas Elétricas': 1},
                  'hrs_max': 12,
                  'hrs_min': 8,
                  'nome': 'Fabiano'},
                 {'disciplinas': {'Controle I': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Alexsandro'},
                 {'disciplinas': {'Princípios de Comunicações': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Fabrício'},
                 {'disciplinas': {'Sistemas Elétricos': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Clivaldo'},
                 {'disciplinas': {'Eletrônica de Potência': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Romero'},
                 {'disciplinas': {'Técnicas de Medição': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Yuri'},
                 {'disciplinas': {'Análise de Sistemas Elétricos': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Helon'},
                 {'disciplinas': {'Filtros': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Euler'},
                 {'disciplinas': {'Instrumentação Industrial': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Carlos'},
                 {'disciplinas': {'Acionamentos e Circuitos Elétricos': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Isaac'},
                 {'disciplinas': {'Microc e Microp': 2},
                  'hrs_max': 8,
                  'hrs_min': 8,
                  'nome': 'Protásio'}],
 'salas': [{'capacidade': 30, 'nome': 'CTM1'},
           {'capacidade': 30, 'nome': 'CTM2'},
           {'capacidade': 30, 'nome': 'CTM3'},
           {'capacidade': 30, 'nome': 'CTM4'}]}
